language: go

go:
  - 1.7
  - 1.8

os:
  - linux
  - osx

env:
  matrix:
    - BUILD_GOARCH=amd64
    - BUILD_GOARCH=386

before_install:
  - go get -u honnef.co/go/tools/cmd/gosimple
  - go get -u honnef.co/go/tools/cmd/staticcheck
  - go get -u honnef.co/go/tools/cmd/unused

# don't go get deps. will only build with code in vendor directory.
install: true

script:
  # pkgs avoids testing anything in vendor/
  - pkgs=$(go list ./... | grep -v /vendor/)
  - go_files=$(find . -iname '*.go' | grep -v /vendor/)
  - test -z $(gofmt -s -l $go_files)
  - go vet $pkgs
  - staticcheck $pkgs
  - go test -v -race $pkgs
  - gosimple $pkgs
  - unused $pkgs
